#!/usr/bin/env bash
# scripts/ai/worktree-alloc.sh — deterministic per-worktree resource allocation. Core file.
#
# Parallel worktrees share one machine: same ports, same dev DB, same caches. Without allocation two
# agents silently fight over them and the failure looks like a code bug. This assigns each worktree a
# stable index and writes .tasks/_worktree.env — the project decides what to do with the values.
#
#   worktree-alloc.sh          → allocate + write .tasks/_worktree.env, print it
#   worktree-alloc.sh --print  → print without writing
#
# Values: ADW_WORKTREE_INDEX, ADW_PORT_BASE, ADW_DB_SCHEMA, ADW_BRANCH, ADW_WORKTREE_DIR.
set -uo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$here/lib.sh"

root="$(adw_repo_root)" || adw_die "not a git repo"
cd "$root" || adw_die "cannot enter the repository root: $root"

# Index = position in `git worktree list` (stable while the worktree exists).
index=0; n=0
while IFS= read -r line; do
  dir="${line%% *}"
  [[ "$dir" == "$root" ]] && index=$n
  n=$((n+1))
done < <(git worktree list --porcelain | awk '/^worktree /{print substr($0,10)}')

port_base="$(adw_cfg PORT_BASE 4000)"
stride="$(adw_cfg PORT_STRIDE 10)"
prefix="$(adw_cfg DB_SCHEMA_PREFIX adw_)"
branch="$(git rev-parse --abbrev-ref HEAD)"
slug="$(printf '%s' "$branch" | tr -c 'a-zA-Z0-9' '_' | tr 'A-Z' 'a-z' | cut -c1-40)"

env_body="$(cat <<EOF
# Generated by scripts/ai/worktree-alloc.sh — do not commit. One line per allocated resource.
ADW_WORKTREE_INDEX=$index
ADW_WORKTREE_DIR=$root
ADW_BRANCH=$branch
ADW_PORT_BASE=$(( port_base + index * stride ))
ADW_DB_SCHEMA=${prefix}${slug}
EOF
)"

if [[ "${1:-}" == "--print" ]]; then printf '%s\n' "$env_body"; exit 0; fi

mkdir -p .tasks
printf '%s\n' "$env_body" > .tasks/_worktree.env

common_git="$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null)"
excl="$common_git/worktrees/$(basename "$root")/info/exclude"
[[ -d "$(dirname "$excl")" ]] || excl="$common_git/info/exclude"
mkdir -p "$(dirname "$excl")"
grep -qxF '.tasks/_worktree.env' "$excl" 2>/dev/null || printf '%s\n' '.tasks/_worktree.env' >> "$excl"

adw_log "allocated worktree #$index → ports from $(( port_base + index * stride )), schema ${prefix}${slug}"
adw_log "source it before running the app:  set -a; . .tasks/_worktree.env; set +a"
printf '%s\n' "$env_body"
